dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Scoder_Cpython_Sops_S_Ucoder_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/coder/python/ops/_coder_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Srnn_Cpython_Sops_S_Ugru_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Srnn_Cpython_Sops_S_Ulstm_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/rnn/python/ops/_lstm_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Slayers_Cpython_Sops_S_Usparse_Ufeature_Ucross_Uop.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/layers/python/ops/_sparse_feature_cross_op.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Sdata_C_Udataset_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/data/python/ops/../../_dataset_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Snccl_Cpython_Sops_S_Unccl_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/nccl/python/ops/_nccl_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Sinput_Upipeline_Cpython_Sops_S_Uinput_Upipeline_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/input_pipeline/python/ops/_input_pipeline_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Sfactorization_Cpython_Sops_S_Uclustering_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/factorization/python/ops/_clustering_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Sfactorization_Cpython_Sops_S_Ufactorization_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/factorization/python/ops/_factorization_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Stpu_Cpython_Sops_S_Utpu_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/tpu/python/ops/_tpu_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Simage_Cpython_Sops_S_Udistort_Uimage_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/image/python/ops/_distort_image_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Simage_Cpython_Sops_S_Uimage_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/image/python/ops/_image_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Simage_Cpython_Sops_S_Usingle_Uimage_Urandom_Udot_Ustereograms.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/image/python/ops/_single_image_random_dot_stereograms.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Smemory_Ustats_Cpython_Sops_S_Umemory_Ustats_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/memory_stats/python/ops/_memory_stats_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Speriodic_Uresample_Cpython_Sops_S_Uperiodic_Uresample_Uop.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/periodic_resample/python/ops/_periodic_resample_op.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Sresampler_Cpython_Sops_S_Uresampler_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Sseq2seq_Cpython_Sops_S_Ubeam_Usearch_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/_beam_search_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Stensor_Uforest_Cpython_Sops_S_Utensor_Uforest_Uops.so___Utensorflow_Scontrib_Stensor_Uforest in /Library/Python/2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_tensor_forest_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Stensor_Uforest_Cpython_Sops_S_Utensor_Uforest_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_tensor_forest_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Stensor_Uforest_Cpython_Sops_S_Umodel_Uops.so___Utensorflow_Scontrib_Stensor_Uforest in /Library/Python/2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_model_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Stensor_Uforest_Cpython_Sops_S_Umodel_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_model_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Stensor_Uforest_Cpython_Sops_S_Ustats_Uops.so___Utensorflow_Scontrib_Stensor_Uforest in /Library/Python/2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_stats_ops.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH $ORIGIN/../../../../../_solib_darwin_x86_64/_U_S_Stensorflow_Scontrib_Stensor_Uforest_Cpython_Sops_S_Ustats_Uops.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_stats_ops.so being ignored in restricted program because it is a relative path
/Users/laurenwatson/lematus_copy/mtl3_nematus/model.py:447: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, 'Unknown output activation function "%s"' % self.config.output_hidden_activation)
/Users/laurenwatson/lematus_copy/mtl3_nematus/model.py:516: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, 'Unknown output activation function "%s"' % self.config.output_hidden_activation)
ERROR: failed to determine vocabulary size from file: ./models_/English-20-char-context-1/data/train-sources.json
Traceback (most recent call last):
  File "nmt.py", line 1322, in <module>
    config = parse_args()
  File "nmt.py", line 1293, in parse_args
    vocab_sizes[i] = max(d.values()) + 1
UnboundLocalError: local variable 'd' referenced before assignment
